services:
  - type: web
    name: ulpin-3d-demo
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.10
      - key: SECRET_KEY
        generateValue: true
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_MODEL
        value: openai/gpt-oss-20b:free
      - key: APP_BASE_URL
        value: https://threed-ulpin-demo.onrender.com
